### ISSUE TITLE
预处理数据集

### ISSUE THREAD

**Issue by MMMMMz** [BunsenFeng/BotRGCN#1]
请问直接下载得到的您处理好的train.json， test.json等文件，这些文件是存在问题的吗？ 是需要重新跑一些您发布（在TwiBot-22中）的预处理代码，自己重新处理一遍吗？因为我在跑对推特文本进行编码的代码处一直报错。

**Comment by leopoldwhite** [comment]
请联系wind_binteng@stu.xjtu.edu.cn获得符合twibot22格式的数据集`TwiBot-20-Format22.zip`

并使用twibot22仓库中的代码
https://github.com/LuoUndergradXJTU/TwiBot-22/tree/master/src/BotRGCN/twibot_20
