### ISSUE TITLE
Something wrong with the pre-process data

### ISSUE THREAD

**Issue by wangyp33** [BunsenFeng/BotRGCN#3]
1. 预处理过的数据与论文里的feature_size不一样   还有把你给的num_properties_tensor.pt打印出来为什么是float类型，不是6维特征吗打印出来为啥是5维，

2.   cat_properties_tensor.pt 11维 打印出来为啥是3维

**Comment by leopoldwhite** [comment]
1. 以上预处理的结果是根据符合Twibot22格式的Twibot20数据集生成的, 具体可见 [here](https://github.com/LuoUndergradXJTU/TwiBot-22/tree/master/src/BotRGCN#:~:text=There%20are%20some%20changes%20in%20user%20numerical%20properties%20%26%20user%20categorical%20properties%20due%20to%20the%20lack%20of%20relevant%20data)，

如果你想要使用原格式的Twibot20数据集去复现文章结果，可以利用 ` Dataset.py` 中的`num_prop_preprocess()` 和 `cat_prop_preprocess()`获得6维的`num_properties_tensor`和11维的`cat_properties_tensor` 

2. 关于num_properties为什么是float类型：
![image](https://user-images.githubusercontent.com/92447967/198544222-738c5dac-0cef-4115-9ca4-733180aa79b6.png)
